---
title: "Ben Allen: Assignment 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data <- read_csv("~/Desktop/SAL 366/CFB_MRP_Data.csv")
data2015 <- mutate(data) %>% filter(data$season == "2015")
```

```{r}
#install.packages("quantreg")
#install.packages("ivreg")
library(quantreg)
library(tidyverse)
library(stargazer)
library(ivreg)
library(lmtest)
library(coeftest)
library(sandwich)
```

```{r}
#1 - OLS + three quantiles

lm_2015 <- lm(realrev ~ market + footballEntertainment + playersall + avgrankpointsthisseason + oppschedulerank, data = data2015)

qm_25 <- rq(realrev ~ market + footballEntertainment + playersall + avgrankpointsthisseason + oppschedulerank, data = data2015, tau = 0.25)

qm_50 <- rq(realrev ~ market + footballEntertainment + playersall + avgrankpointsthisseason + oppschedulerank, data = data2015, tau = 0.50)

qm_75 <- rq(realrev ~ market + footballEntertainment + playersall + avgrankpointsthisseason + oppschedulerank, data = data2015, tau = 0.75)
```

```{r}
summary(lm_2015) -> slm_2015

mean(data2015$playersall)

summary(qm_25) 

summary(qm_50)

summary(qm_75)
```

```{r}
stargazer(lm_2015, qm_25, qm_50, qm_75, column.labels = c("OLS", "0.25", "0.50", "0.75"), type = "html", out = "RealRev.html")

```

```{r}
#2SLS

TwoSLS <- ivreg(realrev ~ market + footballEntertainment + avgrankpointsthisseason + oppschedulerank | playersall | pool + multiyearrate, data = data2015)

summary(TwoSLS)
```

```{r}
#2b - Hausmen Test 
s1 <- lm(playersall ~ pool + multiyearrate + avgrankpointsthisseason +  oppschedulerank + market + footballEntertainment, data = data2015)
residuals = s1$residuals

summary(s1)

s2 <- lm(realrev ~ market + footballEntertainment + playersall + avgrankpointsthisseason + oppschedulerank + residuals, data = data2015)
summary(s2)
```

```{r}
#3a - Clustered SE for playersall
CSE_all <- lm(realrev ~ playersall + as.factor(season) + school, data = data)
se1 <- coeftest(CSE_all,vcov = vcovCL)[,2]

summary(CSE_all)
```

```{r}
#3b - Draft value model with CSE
dv_all <- lm(realrev ~ value + as.factor(season) + school, data = data )
se2 <- coeftest(dv_all,vcov = vcovCL)[,2]

summary(dv_all)
```


```{r}
#3d - combining into 1 table
stargazer(CSE_all, dv_all, se = c(se1, se2), title = "Clustered SE Models", type = "html", out = "CSE_Models.html")
```


```{r}
#4 
lag_rec_model <- lm(realrev ~ market + footballEntertainment + playersall + avgrankpointsthisseason + oppschedulerank + pool + multiyearrate + laggedRecruitingScore + as.factor(season), data = data)

se_lagged <- coeftest(lag_rec_model,vcov = vcovCL)[,2]

summary(lag_rec_model)

stargazer(lag_rec_model, se = c(se_lagged), title = "Lagged Recruiting Model", type = "html", out = "Lagged_Recruiting_Model.html")

```

